# Generated by Django 3.0.4 on 2020-04-22 07:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_num', models.CharField(max_length=50)),
                ('apartment_owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_code', models.CharField(max_length=50)),
                ('building_adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaterCounterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_counter_num', models.CharField(max_length=50)),
                ('water_counter_type', models.CharField(choices=[('CW', 'Cold water'), ('HW', 'Hot water')], default='CW', max_length=5)),
                ('water_counter_setup_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('water_counter_expiration_date', models.DateField()),
                ('water_counter_active', models.BooleanField(default=True)),
                ('apartment_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.ApartmentCategory')),
            ],
        ),
        migrations.CreateModel(
            name='WaterCounterReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_counter_reading', models.DecimalField(decimal_places=3, max_digits=8)),
                ('water_counter_readings_current_date', models.DateField(default=datetime.date.today)),
                ('water_counter_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.WaterCounterCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Lietotaji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lietotajs', models.CharField(max_length=50)),
                ('apartment_tag', models.ManyToManyField(to='water.ApartmentCategory')),
            ],
        ),
        migrations.AddField(
            model_name='apartmentcategory',
            name='building_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.BuildingCategory'),
        ),
    ]
